version: "3.0"

services:
  roach1:
    image: cockroachdb/cockroach:v19.1.5
    command: start --insecure
    expose:
      - "8080"
      - "26257"
    ports:
      - "26257:26257"
      - "8080:8080"
    networks:
      - titanicnet
    volumes:
      - ./cockroach-data/roach1:/cockroach/cockroach-data
  roach2:
    image: cockroachdb/cockroach:v19.1.5
    command: start --insecure --join=roach1
    networks:
      - titanicnet
    volumes:
      - ./cockroach-data/roach2:/cockroach/cockroach-data
  roach3:
    image: cockroachdb/cockroach:v19.1.5
    command: start --insecure --join=roach1
    networks:
      - titanicnet
    volumes:
      - ./cockroach-data/roach3:/cockroach/cockroach-data
  db-init:
    image: cockroachdb/cockroach
    networks:
      - titanicnet
    volumes:
      - ./setup_db.bash:/setup_db.bash
    entrypoint: "/bin/bash"
    command: /setup_db.bash
  titanic-api:
    image: gcr.io/${PROJECT_ID}/titanic-api:latest
    networks:
      - titanicnet
    expose:
      - "3000"
      - "8443"
    ports:
      - "8443:8443"
      - "3000:3000"
    volumes:
      - ./tls:/etc/tls/certs
    depends_on:
      - roach1
      - roach2
      - roach3
      - db-init
networks:
  titanicnet:
