apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: memcached-deployement
  namespace: awx
  labels:
    app: memcached
spec:
  replicas: 1
  selector:
    matchLabels:
      app: memcached
  template:
    metadata:
      labels:
        app: memcached
    spec:
      containers:
        - image: memcached:alpine
          name: memcached
          resources:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 1Gi
---
kind: Service
apiVersion: v1
metadata:
  name: memcached-svc
  namespace: awx
spec:
  selector:
    app: memcached
  ports:
    - protocol: TCP
      port: 11211
      targetPort: 11211
